[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "its-example-templates"
version = "1.0.0"
dependencies = [
    "its-compiler-cli>=1.0.0",
    "rich>=13.0.0",
]
