[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "its-example-templates"
version = "1.0.0"
dependencies = [
    "its-compiler-python[dev] @ git+https://github.com/AlexanderParker/its-compiler-python.git",
    "rich>=13.0.0",
]
